Do not launchGcmRegistration if never registered
On clean flash and WhisperPush has never run before, the default
return value for last registration timestamp is -1. This means,
the user never had tried to register with the service before.
So unless this value is != -1 do not automatically run the
launchGcmRegistration() check as it causes exceptions if no
gapps are installed yet.

Log excerpt:
GcmRecurringRegistration
java.io.IOException: SERVICE_NOT_AVAILABLE
at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source)
at org.whispersystems.whisperpush.gcm.GcmHelper.getRegistrationId(GcmHelper.java:65)
at org.whispersystems.whisperpush.WhisperPush$1.doInBackground(WhisperPush.java:52)

Change-Id: Ic7c675bd366ab34be30b0b106d476eb137a28c16