launchGcmRegistration: check if lastRegistered != -1
This is an addition to http://review.cyanogenmod.org/#/c/100987
The directory listener may fire launchGcmRegistration too
even though no registration may have happened and thus result
in an unneeded exception:
java.io.IOException: SERVICE_NOT_AVAILABLE

Change-Id: Iba9ea8ca99feea514306d9dbc84c275d7f8f5326